# docker-compose.yml
version: '3.8'

services:
    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

    php:
        build: .
        volumes:
            - .:/var/www/html
        environment:
            # Override this if you need a different URL
            DATABASE_URL: mysql://symfony:symfony@db:3306/symfony
        depends_on:
            db:
                condition: service_healthy

    nginx:
        image: nginx:1.21-alpine
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html:ro
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - php

volumes:
    db_data:
